# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_mng', '0002_auto_20190924_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
